e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls"), name='home'),
    path('users/', include("users.urls"), name='users'),
    path('orders/', include("orders.urls"), name='orders'),
]

orders/urls.py
from django.urls import path
from .views import create_order, all_orders_page, my_orders_page

app_name = 'orders'
urlpatterns = [
    path('create-order/<slug:slug>', create_order, name='create_order'),
    path('all-orders/', all_orders_page, name='all-orders'),
    path('my-orders/', my_orders_page, name='my-orders'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
    path('', views.home_page, name='index'),
    path('products/<slug:slug>/', views.detail_page, name='detail'),
    path('products/<slug:slug>/reviews/<int:id>/', views.delete_review, name='delete_review'),
    path('products/<slug:slug>/edit_review/<int:id>/', views.edit_review, name='edit_review'),
    path('create-product/', views.create_product, name='create_product'),

]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_page, name='logout'),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    address = models.CharField(max_length=250)
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.PositiveIntegerField()
    order_status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product.name} is ordered by {self.user.username}"

    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.product.price
        super().save(*args, **kwargs)



# class OrderItem(models.Model):
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.IntegerField(default=1)
#
#     def __str__(self):
#         return f"{self.quantity} of {self.product.name} in Order {self.order.id}"

orders/views.py
from django.shortcuts import get_object_or_404, render, redirect

from orders.models import Order
from products.models import Product


def create_order(request, slug):
    if request.method == 'POST':
        product = get_object_or_404(Product, slug=slug)
        quantity = int(request.POST['quantity'])
        address = request.POST['address']
        Order.objects.create(user=request.user, product=product, quantity=quantity, address=address)
        return redirect('products:index')
    else:
        product = get_object_or_404(Product, slug=slug)
    return render(request, 'create_order.html', {'product': product})


def my_orders_page(request):
    orders = Order.objects.all().filter(user=request.user).order_by('-order_date')
    context = {'orders': orders}
    return render(request, 'orders.html', context)


def all_orders_page(request):
    orders = Order.objects.all().order_by('-order_date')
    context = {'orders': orders}
    return render(request, 'orders.html', context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'products:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'products:index' %}?category={{ category.id }}">{{ category.name }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="qidiruv"
                       value="{{ search_query }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff %}
                        <a href="{% url 'orders:all-orders' %}" class="btn btn-warning ms-3">All orders</a>
                        <a href="{% url 'products:create_product' %}" class="btn btn-warning ms-3">Create Product</a>
                    {% else %}
                        <a href="{% url 'orders:my-orders' %}" class="btn btn-warning ms-3">My orders</a>
                    {% endif %}
                    <a href="{% url 'users:logout' %}" class="btn btn-warning ms-3">Logout</a>
                {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-success mx-3">Register</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </form>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>


</body>
</html>

templates/create_order.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <h3>{{ product.name }}</h3>
                <form method="post" class="form-control">
                    {% csrf_token %}
                    <label for="quantity">Mahsulot soni:</label><br>
                    <input type="number" id="quantity" name="quantity">
                    <label for="address">Mahsulot yetkazib berilishi kerak bo'lgan adres:</label><br>
                    <input type="text" id="address" name="address"><br><br>

                    <button class="btn btn-primary">Buyurtmani tasdiqlash</button>
                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/create_product.html
{% extends 'base.html' %}

{% block title %}Edit review{% endblock %}

{% block content %}
    <div class="container">
    <div class="col-md-12">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 py-3">
                <form method="POST" class="form-control" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-warning" type="submit">Create_product</button>
    </form>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/edit_review.html
{% extends 'base.html' %}

{% block title %}Edit review{% endblock %}

{% block content %}

    <form method="POST" class="form-control">
    
        {% csrf_token %}
    
        {{ form.as_p }}
    
        <button class="btn btn-warning" type="submit">Edit review</button>
    </form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

{#    <header>#}
{#        <nav>#}
{#            <ul>#}
{#                {%  %}#}
{#                <li></li>#}
{#            </ul>#}
{#        </nav>#}
{#    </header>#}

    <h1>E commerce website</h1>
    <div class="container">
        <div class="col-md-12 p-5">
            <div class="row">
                {% for product in products %}
                    <div class="card" style="width: 18rem;">
                        <img src="{{ product.product_image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <a href="{% url 'products:detail' product.slug %}">
                                <h5 class="card-title">{{ product.name }}</h5>
                            </a>
                            <p class="card-text">{{ product.description | truncatechars:100 }}</p>
                            <a href="{% url 'orders:create_order' product.slug %}" class="btn btn-primary">Get order</a>
                            <span class="ms-5 fw-bolder">${{ product.price }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-12 p-5">
            <form method="POST">
                {% csrf_token %}
                {{ login_form }}
                <button class="btn btn-primary" type="submit">Login</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="col-md 12">
        <div class="row">
            <div class="col-md-12 py-5">
                <ul class="list-group">
                    {% for order in orders %}

                        <li class="list-group-item d-flex justify-content-between">
                            <p>{{ order.product.name }}</p>
                            <p>{{ order.user.username }}</p>
                            <p>{{ order.order_date }}</p>
                            <p>{{ order.address }}</p>

                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}Detail page{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-md-12 py-5">
            <h1>{{ product.name }}</h1>
            <div class="row py-5">
                <div class="col-md-4">
                    <img src="{{ product.product_image.url }}" alt="{{ product.name }}">
                </div>
                <div class="col-md-4 card">
                    <h3>{{ product.description }}</h3>
                </div>
                <div class="col-md-4 card">
                    <h3>{{ product.price }}</h3>
                    <p>Standart yetkazib berish
                        Manzilga qarab 4 soatdan 3 kungacha yetkazib beriladi</p>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'orders:create_order' product.slug %}" class="btn btn-success">Buyurtma
                            berish</a>
                    {% else %}
                        <h3>Buyurtma berish uchun ro'yxatdan o'ting</h3>
                        <a href="{% url 'users:register' %}" class="btn btn-primary">Register</a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                {% if request.user.is_authenticated %}
                    <div class="col-md-6">
                        <form class="form-control" action="" method="post">
                            {% csrf_token %}
                            <textarea name="review" id="review" cols="52" rows="3"></textarea>
                            <br>
                            <button class="btn btn-primary" type="submit">Send Review</button>
                        </form>
                    </div>
                {% else %}
                    <div class="col-md-4">
                        <p>Siz review qoldirish uchun ro'yxatdan o'tgan bo'lishingiz kerak</p>
                        <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
                    </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        {% for review in product_reviews %}
                            <li class="list-group-item">
                                <h5>{{ review.user.username }} | {{ review.created_at }}
                                    <a class="btn btn-warning"
                                       href="{% url 'products:edit_review' product.slug review.id %}">edit</a>
                                    <a class="btn btn-danger"
                                       href="{% url 'products:delete_review' product.slug review.id %}">del</a>
                                </h5>
                                <p>{{ review.review }}</p>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-12 p-5">
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-3" type="submit">Sign Up</button>
                <a href="{% url 'users:login' %}" class="btn btn-warning ms-3 mt-3">Login</a>
            </form>
        </div>
    </div>


{% endblock %}